-- Insert players into Player
INSERT INTO Player (player_name, share_rounds) VALUES ('Player1', 1);
INSERT INTO Player (player_name, share_rounds) VALUES ('Player2', 1);
INSERT INTO Player (player_name, share_rounds) VALUES ('Player3', 1);
INSERT INTO Player (player_name, share_rounds) VALUES ('Player4', 1);
INSERT INTO Player (player_name, share_rounds) VALUES ('Player5', 1);
INSERT INTO Player (player_name, share_rounds) VALUES ('Player6', 1);
INSERT INTO Player (player_name, share_rounds) VALUES ('Player7', 1);
INSERT INTO Player (player_name, share_rounds) VALUES ('Player8', 1);
INSERT INTO Player (player_name, share_rounds) VALUES ('Player9', 1);
INSERT INTO Player (player_name, share_rounds) VALUES ('Player10', 1);

-- Insert games into Game
INSERT INTO Game (tournament_flag, buy_in, num_rounds) VALUES (1, 195, 7);
INSERT INTO Game (tournament_flag, buy_in, num_rounds) VALUES (1, 140, 10);
INSERT INTO Game (tournament_flag, buy_in, num_rounds) VALUES (0, 0, 4);
INSERT INTO Game (tournament_flag, buy_in, num_rounds) VALUES (0, 0, 8);
INSERT INTO Game (tournament_flag, buy_in, num_rounds) VALUES (0, 0, 8);

-- Insert courses into Course
INSERT INTO Course (course_name, course_rating, slope_rating, par) VALUES ('Magic Kingdom', 31.7, 47, 36);
INSERT INTO Course (course_name, course_rating, slope_rating, par) VALUES ('Epcot', 31.8, 50, 35);
INSERT INTO Course (course_name, course_rating, slope_rating, par) VALUES ('Hollywood Studios', 32.9, 53, 37);
INSERT INTO Course (course_name, course_rating, slope_rating, par) VALUES ('Animal Kingdom', 36.4, 51, 37);
INSERT INTO Course (course_name, course_rating, slope_rating, par) VALUES ('Universal Studios', 33.3, 45, 37);
INSERT INTO Course (course_name, course_rating, slope_rating, par) VALUES ('Islands of Adventure', 31.2, 57, 38);
INSERT INTO Course (course_name, course_rating, slope_rating, par) VALUES ('Volcano Bay', 33.3, 55, 36);
INSERT INTO Course (course_name, course_rating, slope_rating, par) VALUES ('SeaWorld', 34.5, 49, 35);
INSERT INTO Course (course_name, course_rating, slope_rating, par) VALUES ('Busch Gardens', 36.1, 59, 34);
INSERT INTO Course (course_name, course_rating, slope_rating, par) VALUES ('Legoland', 33.4, 58, 32);

-- Insert rounds into Round and scores into Score
INSERT INTO Round (game_id, player_id, round_num, course_id, raw_score) VALUES (1, 3, 1, 8, 60);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 1, 9);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 2, 4);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 3, 5);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 4, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 5, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 6, 5);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 7, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 8, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 9, 10);
INSERT INTO Round (game_id, player_id, round_num, course_id, raw_score) VALUES (1, 2, 2, 5, 60);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 1, 4);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 2, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 3, 9);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 4, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 5, 9);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 6, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 7, 9);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 8, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 9, 10);
INSERT INTO Round (game_id, player_id, round_num, course_id, raw_score) VALUES (1, 9, 3, 2, 64);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 1, 9);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 2, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 3, 4);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 4, 4);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 5, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 6, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 7, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 8, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 9, 7);
INSERT INTO Round (game_id, player_id, round_num, course_id, raw_score) VALUES (1, 5, 4, 1, 54);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 1, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 2, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 3, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 4, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 5, 9);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 6, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 7, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 8, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 9, 8);
INSERT INTO Round (game_id, player_id, round_num, course_id, raw_score) VALUES (1, 8, 5, 3, 69);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (5, 1, 4);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (5, 2, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (5, 3, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (5, 4, 5);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (5, 5, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (5, 6, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (5, 7, 5);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (5, 8, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (5, 9, 4);
INSERT INTO Round (game_id, player_id, round_num, course_id, raw_score) VALUES (1, 5, 6, 10, 63);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (6, 1, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (6, 2, 5);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (6, 3, 5);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (6, 4, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (6, 5, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (6, 6, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (6, 7, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (6, 8, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (6, 9, 4);
INSERT INTO Round (game_id, player_id, round_num, course_id, raw_score) VALUES (1, 4, 7, 3, 77);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (7, 1, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (7, 2, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (7, 3, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (7, 4, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (7, 5, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (7, 6, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (7, 7, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (7, 8, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (7, 9, 10);
INSERT INTO Round (game_id, player_id, round_num, course_id, raw_score) VALUES (2, 1, 1, 10, 70);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 1, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 2, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 3, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 4, 4);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 5, 5);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 6, 4);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 7, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 8, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 9, 7);
INSERT INTO Round (game_id, player_id, round_num, course_id, raw_score) VALUES (2, 7, 2, 3, 59);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 1, 9);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 2, 9);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 3, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 4, 9);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 5, 4);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 6, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 7, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 8, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 9, 8);
INSERT INTO Round (game_id, player_id, round_num, course_id, raw_score) VALUES (2, 5, 3, 5, 56);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 1, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 2, 4);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 3, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 4, 9);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 5, 5);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 6, 4);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 7, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 8, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 9, 7);
INSERT INTO Round (game_id, player_id, round_num, course_id, raw_score) VALUES (2, 6, 4, 10, 61);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 1, 5);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 2, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 3, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 4, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 5, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 6, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 7, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 8, 5);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 9, 7);
INSERT INTO Round (game_id, player_id, round_num, course_id, raw_score) VALUES (2, 1, 5, 7, 56);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (5, 1, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (5, 2, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (5, 3, 9);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (5, 4, 4);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (5, 5, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (5, 6, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (5, 7, 9);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (5, 8, 5);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (5, 9, 8);
INSERT INTO Round (game_id, player_id, round_num, course_id, raw_score) VALUES (2, 6, 6, 10, 70);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (6, 1, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (6, 2, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (6, 3, 5);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (6, 4, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (6, 5, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (6, 6, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (6, 7, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (6, 8, 4);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (6, 9, 5);
INSERT INTO Round (game_id, player_id, round_num, course_id, raw_score) VALUES (2, 3, 7, 1, 66);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (7, 1, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (7, 2, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (7, 3, 5);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (7, 4, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (7, 5, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (7, 6, 9);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (7, 7, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (7, 8, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (7, 9, 7);
INSERT INTO Round (game_id, player_id, round_num, course_id, raw_score) VALUES (2, 2, 8, 4, 65);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (8, 1, 9);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (8, 2, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (8, 3, 9);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (8, 4, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (8, 5, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (8, 6, 5);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (8, 7, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (8, 8, 9);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (8, 9, 9);
INSERT INTO Round (game_id, player_id, round_num, course_id, raw_score) VALUES (2, 4, 9, 2, 59);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (9, 1, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (9, 2, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (9, 3, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (9, 4, 5);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (9, 5, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (9, 6, 4);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (9, 7, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (9, 8, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (9, 9, 4);
INSERT INTO Round (game_id, player_id, round_num, course_id, raw_score) VALUES (2, 5, 10, 6, 62);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (10, 1, 9);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (10, 2, 9);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (10, 3, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (10, 4, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (10, 5, 5);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (10, 6, 4);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (10, 7, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (10, 8, 4);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (10, 9, 9);
INSERT INTO Round (game_id, player_id, round_num, course_id, raw_score) VALUES (3, 4, 1, 1, 69);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 1, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 2, 5);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 3, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 4, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 5, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 6, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 7, 9);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 8, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 9, 7);
INSERT INTO Round (game_id, player_id, round_num, course_id, raw_score) VALUES (3, 10, 2, 8, 70);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 1, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 2, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 3, 9);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 4, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 5, 9);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 6, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 7, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 8, 9);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 9, 8);
INSERT INTO Round (game_id, player_id, round_num, course_id, raw_score) VALUES (3, 7, 3, 5, 51);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 1, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 2, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 3, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 4, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 5, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 6, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 7, 5);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 8, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 9, 10);
INSERT INTO Round (game_id, player_id, round_num, course_id, raw_score) VALUES (3, 4, 4, 2, 57);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 1, 9);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 2, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 3, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 4, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 5, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 6, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 7, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 8, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 9, 10);
INSERT INTO Round (game_id, player_id, round_num, course_id, raw_score) VALUES (4, 1, 1, 8, 66);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 1, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 2, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 3, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 4, 4);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 5, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 6, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 7, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 8, 4);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 9, 5);
INSERT INTO Round (game_id, player_id, round_num, course_id, raw_score) VALUES (4, 4, 2, 1, 72);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 1, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 2, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 3, 5);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 4, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 5, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 6, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 7, 9);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 8, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 9, 6);
INSERT INTO Round (game_id, player_id, round_num, course_id, raw_score) VALUES (4, 4, 3, 2, 63);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 1, 5);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 2, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 3, 5);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 4, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 5, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 6, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 7, 4);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 8, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 9, 7);
INSERT INTO Round (game_id, player_id, round_num, course_id, raw_score) VALUES (4, 8, 4, 10, 68);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 1, 5);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 2, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 3, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 4, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 5, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 6, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 7, 5);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 8, 5);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 9, 5);
INSERT INTO Round (game_id, player_id, round_num, course_id, raw_score) VALUES (4, 1, 5, 5, 70);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (5, 1, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (5, 2, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (5, 3, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (5, 4, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (5, 5, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (5, 6, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (5, 7, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (5, 8, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (5, 9, 6);
INSERT INTO Round (game_id, player_id, round_num, course_id, raw_score) VALUES (4, 6, 6, 10, 46);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (6, 1, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (6, 2, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (6, 3, 4);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (6, 4, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (6, 5, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (6, 6, 4);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (6, 7, 4);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (6, 8, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (6, 9, 4);
INSERT INTO Round (game_id, player_id, round_num, course_id, raw_score) VALUES (4, 4, 7, 10, 72);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (7, 1, 4);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (7, 2, 5);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (7, 3, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (7, 4, 9);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (7, 5, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (7, 6, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (7, 7, 4);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (7, 8, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (7, 9, 8);
INSERT INTO Round (game_id, player_id, round_num, course_id, raw_score) VALUES (4, 3, 8, 8, 66);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (8, 1, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (8, 2, 9);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (8, 3, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (8, 4, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (8, 5, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (8, 6, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (8, 7, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (8, 8, 4);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (8, 9, 6);
INSERT INTO Round (game_id, player_id, round_num, course_id, raw_score) VALUES (5, 4, 1, 9, 58);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 1, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 2, 5);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 3, 5);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 4, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 5, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 6, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 7, 5);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 8, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (1, 9, 9);
INSERT INTO Round (game_id, player_id, round_num, course_id, raw_score) VALUES (5, 5, 2, 8, 65);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 1, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 2, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 3, 4);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 4, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 5, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 6, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 7, 5);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 8, 4);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (2, 9, 9);
INSERT INTO Round (game_id, player_id, round_num, course_id, raw_score) VALUES (5, 6, 3, 9, 65);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 1, 5);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 2, 9);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 3, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 4, 4);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 5, 4);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 6, 5);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 7, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 8, 4);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (3, 9, 5);
INSERT INTO Round (game_id, player_id, round_num, course_id, raw_score) VALUES (5, 2, 4, 8, 60);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 1, 4);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 2, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 3, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 4, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 5, 4);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 6, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 7, 9);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 8, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (4, 9, 6);
INSERT INTO Round (game_id, player_id, round_num, course_id, raw_score) VALUES (5, 7, 5, 8, 60);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (5, 1, 9);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (5, 2, 4);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (5, 3, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (5, 4, 4);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (5, 5, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (5, 6, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (5, 7, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (5, 8, 4);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (5, 9, 7);
INSERT INTO Round (game_id, player_id, round_num, course_id, raw_score) VALUES (5, 3, 6, 10, 54);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (6, 1, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (6, 2, 5);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (6, 3, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (6, 4, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (6, 5, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (6, 6, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (6, 7, 9);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (6, 8, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (6, 9, 9);
INSERT INTO Round (game_id, player_id, round_num, course_id, raw_score) VALUES (5, 2, 7, 4, 75);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (7, 1, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (7, 2, 9);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (7, 3, 4);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (7, 4, 5);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (7, 5, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (7, 6, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (7, 7, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (7, 8, 9);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (7, 9, 6);
INSERT INTO Round (game_id, player_id, round_num, course_id, raw_score) VALUES (5, 2, 8, 3, 60);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (8, 1, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (8, 2, 8);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (8, 3, 9);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (8, 4, 9);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (8, 5, 6);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (8, 6, 7);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (8, 7, 4);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (8, 8, 10);
INSERT INTO Score (round_id, hole_number, hole_score) VALUES (8, 9, 6);

-- Insert trending handicaps into TrendingHandicap
INSERT INTO TrendingHandicap (player_id, trending_handicap) VALUES (1, 22);
INSERT INTO TrendingHandicap (player_id, trending_handicap) VALUES (2, 22);
INSERT INTO TrendingHandicap (player_id, trending_handicap) VALUES (3, 8);
INSERT INTO TrendingHandicap (player_id, trending_handicap) VALUES (4, 4);
INSERT INTO TrendingHandicap (player_id, trending_handicap) VALUES (5, 15);
INSERT INTO TrendingHandicap (player_id, trending_handicap) VALUES (6, 19);
INSERT INTO TrendingHandicap (player_id, trending_handicap) VALUES (7, 9);
INSERT INTO TrendingHandicap (player_id, trending_handicap) VALUES (8, 3);
INSERT INTO TrendingHandicap (player_id, trending_handicap) VALUES (9, 4);
INSERT INTO TrendingHandicap (player_id, trending_handicap) VALUES (10, 12);
