# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '14.0'

target 'ScoreCards' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ScoreCards
  pod 'GoogleSignIn', '~> 7.0'

  pod 'GoogleSignInSwiftSupport'

  target 'ScoreCardsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ScoreCardsUITests' do
    # Pods for testing
  end

end
